# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('counter', models.IntegerField(default=0)),
                ('counter_limit', models.IntegerField(default=300)),
            ],
        ),
    ]
